<center><b>CTS2000: Scripting for the Humanities</b></center>
<center>6-1: Pandas</center>

---

# Introduction to Pandas
### Working with Tabular Data for Text Analysis

---

**What we'll cover:**

1. What is a DataFrame? Building one from scratch
2. Exploring a DataFrame
3. Selecting columns, rows, and cells
4. Boolean (conditional) subsetting
5. Adding and modifying columns
6. Sorting, grouping, and counting
7. Handling missing data

---
## 0. Import pandas

Pandas is a library for working with tabular data. We import it with the standard alias `pd`.

In [ ]:
import string

string.punctuation

In [1]:
import pandas as pd

There are a lot of resources on `pandas` as they are one of the most commonly used libraries in computational humanites. You can start [here](https://www.w3schools.com/python/pandas/default.asp) and make sure to take a look at [this](https://github.com/dlab-berkeley/Python-Data-Wrangling)

---
## 1. What is a DataFrame?

A **DataFrame** is a two-dimensional table — like a spreadsheet — where each column holds a named field, and each row is one record. Pandas is designed around this object.

Before loading our real dataset, let's build a small one from scratch. We'll use data on the world's most spoken languages (source: Ethnologue 2026 through [Wikipedia](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers)), which is very much on-topic for this workshop.

The easiest way to create a DataFrame by hand is to pass a **dictionary** to `pd.DataFrame()`. Each key becomes a column name; each value is a list of entries for that column.

In [2]:
languages_dict = {
    "language": [
        "English", "Mandarin Chinese", "Hindi", "Spanish", "Modern Standard Arabic", "French", "Bengali", "Portuguese", "Indonesian", "Urdu","Russian", "Standard German", "Japanese", "Nigerian Pidgin", "Egyptian Arabic"],
    "family": [
        "Indo-European", "Sino-Tibetan", "Indo-European", "Indo-European", "Afro-Asiatic", "Indo-European", "Indo-European", "Indo-European", "Austronesian", "Indo-European", "Indo-European", "Indo-European", "Japonic", "English Creole", "Afro-Asiatic"],
    "branch": [
        "Germanic", "Sinitic", "Indo-Aryan", "Romance", "Semitic", "Romance", "Indo-Aryan", "Romance", "Malayo-Polynesian", "Indo-Aryan", "Balto-Slavic", "Germanic", None, "Krio", "Semitic"],
    "l1_speakers_m": [372, 988, 347, 487, 0, 75, 234, 252, 78, 78, 133, 76, 124, 5, 83],
    "l2_speakers_m": [1121, 194, 264, 75, 335, 258, 43, 18, 177, 168, 77, 57, 2, 116, 35]
}

In [3]:
languages_dict.keys()

dict_keys(['language', 'family', 'branch', 'l1_speakers_m', 'l2_speakers_m'])

In [4]:
languages_dict["language"]

['English',
 'Mandarin Chinese',
 'Hindi',
 'Spanish',
 'Modern Standard Arabic',
 'French',
 'Bengali',
 'Portuguese',
 'Indonesian',
 'Urdu',
 'Russian',
 'Standard German',
 'Japanese',
 'Nigerian Pidgin',
 'Egyptian Arabic']

In [5]:
languages = pd.DataFrame({
    "language": [
        "English", "Mandarin Chinese", "Hindi", "Spanish", "Modern Standard Arabic", "French", "Bengali", "Portuguese", "Indonesian", "Urdu","Russian", "Standard German", "Japanese", "Nigerian Pidgin", "Egyptian Arabic"],
    "family": [
        "Indo-European", "Sino-Tibetan", "Indo-European", "Indo-European", "Afro-Asiatic", "Indo-European", "Indo-European", "Indo-European", "Austronesian", "Indo-European", "Indo-European", "Indo-European", "Japonic", "English Creole", "Afro-Asiatic"],
    "branch": [
        "Germanic", "Sinitic", "Indo-Aryan", "Romance", "Semitic", "Romance", "Indo-Aryan", "Romance", "Malayo-Polynesian", "Indo-Aryan", "Balto-Slavic", "Germanic", None, "Krio", "Semitic"],
    "l1_speakers_m": [372, 988, 347, 487, 0, 75, 234, 252, 78, 78, 133, 76, 124, 5, 83],
    "l2_speakers_m": [1121, 194, 264, 75, 335, 258, 43, 18, 177, 168, 77, 57, 2, 116, 35]
})
languages

,language,family,branch,l1_speakers_m,l2_speakers_m
0,English,Indo-European,Germanic,372,1121
1,Mandarin Chinese,Sino-Tibetan,Sinitic,988,194
2,Hindi,Indo-European,Indo-Aryan,347,264
3,Spanish,Indo-European,Romance,487,75
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335
5,French,Indo-European,Romance,75,258
6,Bengali,Indo-European,Indo-Aryan,234,43
7,Portuguese,Indo-European,Romance,252,18
8,Indonesian,Austronesian,Malayo-Polynesian,78,177
9,Urdu,Indo-European,Indo-Aryan,78,168
10,Russian,Indo-European,Balto-Slavic,133,77
11,Standard German,Indo-European,Germanic,76,57
12,Japanese,Japonic,NaN,124,2
13,Nigerian Pidgin,English Creole,Krio,5,116
14,Egyptian Arabic,Afro-Asiatic,Semitic,83,35

Notice the structure:
- **Rows** are individual languages (records). Each gets an integer **index** on the left (0, 1, 2…).
- **Columns** are fields: `language`, `family`, `branch` (subcategory of language family) and speaker counts for L1 (first language) and L2 (second language) speaker. The speaker counts are in millions.

---

## 2. Exploring the DataFrame

### Data Frame methods

The `.head()` method will show the first five rows by default. Put an integer in the parentheses to specify a different number of rows. 

`.describe()` provides basic summary statistics. 

`.info()` provides an overview of what is in the dataframe

In [6]:
languages.head()

,language,family,branch,l1_speakers_m,l2_speakers_m
0,English,Indo-European,Germanic,372,1121
1,Mandarin Chinese,Sino-Tibetan,Sinitic,988,194
2,Hindi,Indo-European,Indo-Aryan,347,264
3,Spanish,Indo-European,Romance,487,75
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335

In [7]:
languages.head(7)

,language,family,branch,l1_speakers_m,l2_speakers_m
0,English,Indo-European,Germanic,372,1121
1,Mandarin Chinese,Sino-Tibetan,Sinitic,988,194
2,Hindi,Indo-European,Indo-Aryan,347,264
3,Spanish,Indo-European,Romance,487,75
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335
5,French,Indo-European,Romance,75,258
6,Bengali,Indo-European,Indo-Aryan,234,43

In [8]:
languages.describe()

       l1_speakers_m  l2_speakers_m
count      15.000000       15.00000
mean      222.133333      196.00000
std       255.477946      274.86828
min         0.000000        2.00000
25%        77.000000       50.00000
50%       124.000000      116.00000
75%       299.500000      226.00000
max       988.000000     1121.00000

In [9]:
languages.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   language       15 non-null     str
 1   family         15 non-null     str
 2   branch         14 non-null     str
 3   l1_speakers_m  15 non-null     int64
 4   l2_speakers_m  15 non-null     int64
dtypes: int64(2), str(3)
memory usage: 732.0 bytes

<div style="background: rgba(167, 139, 250, 0.12); border-radius: 6px; padding: 0.6em 1em; margin: 1.5em 0; font-weight: 500;">
 What is the difference between .describe() and .info()?
</div>

Both give you a quick overview of a DataFrame, but they answer different questions:

- **.info()** tells you about structure — column names, how many non-null values, and data types. Good for spotting missing data and checking that columns loaded as the right type.
- **.describe()** tells you about distributions — mean, min, max, quartiles, etc. Numeric columns only by default.

> Do we have an non-null values in our languages dataframe?

### Dataframe attributes

You can call [attributes](https://medium.com/@shawnnkoski/pandas-attributes-867a169e6d9b) of a Pandas variable by using "dot notation" - but without the parentheses to unpack more information.

Here is how we can get all the column names. Surprisingly (or unsurprisinly) very useful when you have quite a few column or not sure about how you spelled something because:

**You must spell the column names in your code exactly as they apper in the dataframe**

In [10]:
languages.columns

Index(['language', 'family', 'branch', 'l1_speakers_m', 'l2_speakers_m'], dtype='str')

Similarly, you can use `.dtypes` (as in data types) to get what kind of data you have stored in each column. Data types here refer to the data types we learnt in notebook `1-5_data_types`.

This is very handy because as you remember, we cannot do every operation with every data types. You can't add an integer with a string.

In [11]:
languages.dtypes

language           str
family             str
branch             str
l1_speakers_m    int64
l2_speakers_m    int64
dtype: object

Some other common data types are:

- int64 (integers)
- float64 (floating-point numbers)
- object (usually strings or mixed types)
- bool (boolean True/False)
- datetime64 (dates/times)

We will see some of these in our Montagu dataset

Finally, `.shape` is another very useful attribute. This allow us to see the shape of our DataFrame. It returns the dimensions of the DataFrame as a tuple of `(rows, columns)` — a quick sanity check that your data loaded completely.

This will be even more relevant, when we do some vector calculation in the coming weeks.

In [12]:
languages.shape

(15, 5)

---

## 3. Selecting Columns, Rows, and Cells

### Single column

A single column on its own is called a **Series** — a one-dimensional labelled array.

You select a single column using *single brackets* and the name of the column that you want to select.

In [13]:
languages['family']

0      Indo-European
1       Sino-Tibetan
2      Indo-European
3      Indo-European
4       Afro-Asiatic
5      Indo-European
6      Indo-European
7      Indo-European
8       Austronesian
9      Indo-European
10     Indo-European
11     Indo-European
12           Japonic
13    English Creole
14      Afro-Asiatic
Name: family, dtype: str

In [14]:
# Confirm the types
print(type(languages))             # DataFrame
print(type(languages['family']))   # Series

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

### Multiple columns

Two or more columns together return a **DataFrame**, think of it like a smaller version of your existing df.

You select multiple columns by using *double brackets* and the names of the columns you want to select.

In [15]:
languages[["language", "family"]]

                  language          family
0                  English   Indo-European
1         Mandarin Chinese    Sino-Tibetan
2                    Hindi   Indo-European
3                  Spanish   Indo-European
4   Modern Standard Arabic    Afro-Asiatic
5                   French   Indo-European
6                  Bengali   Indo-European
7               Portuguese   Indo-European
8               Indonesian    Austronesian
9                     Urdu   Indo-European
10                 Russian   Indo-European
11         Standard German   Indo-European
12                Japanese         Japonic
13         Nigerian Pidgin  English Creole
14         Egyptian Arabic    Afro-Asiatic

> 💡 **Why double brackets?**  
> `languages['family']` — single string → returns a **Series**  
> `languages[["language", "family"]]` — list of strings → returns a **DataFrame**

### Accessing one row

In [16]:
# Get the row 6 (0-indexed)

languages[5]

KeyError: 5

> This does not work because square brackets on a DataFrame expect a column name, not a row number. Pandas looks for a column called 5, doesn't find it, and errors.

But of course, there are a lot of ways to access a single row!

### Slicing rows by position

In [17]:
languages[0:5]

,language,family,branch,l1_speakers_m,l2_speakers_m
0,English,Indo-European,Germanic,372,1121
1,Mandarin Chinese,Sino-Tibetan,Sinitic,988,194
2,Hindi,Indo-European,Indo-Aryan,347,264
3,Spanish,Indo-European,Romance,487,75
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335

In [18]:
# Rows 5 through 9 (like slicing a list)

languages[5:10]

     language         family             branch  l1_speakers_m  l2_speakers_m
5      French  Indo-European            Romance             75            258
6     Bengali  Indo-European         Indo-Aryan            234             43
7  Portuguese  Indo-European            Romance            252             18
8  Indonesian   Austronesian  Malayo-Polynesian             78            177
9        Urdu  Indo-European         Indo-Aryan             78            168

In [19]:
# Applying the slicing logic to row 6

languages[5:6]

  language         family   branch  l1_speakers_m  l2_speakers_m
5   French  Indo-European  Romance             75            258

In [20]:
languages[5:6].shape

(1, 5)

We get a dataframe with 1 row and 5 columns

### `.iloc` — integer-based indexing

`.iloc[rows, columns]` uses **integer positions** for both rows and columns.

In [21]:
# Get the row 6 (0-indexed)

languages.iloc[5]

language                French
family           Indo-European
branch                 Romance
l1_speakers_m               75
l2_speakers_m              258
Name: 5, dtype: object

We can use `.iloc` to return non-consecutive rows. Pass in **integers** as a double list.

In [22]:
# Get the 1st, 5th, and 10th rows (0-indexed)

languages.iloc[[0, 4, 9]]

,language,family,branch,l1_speakers_m,l2_speakers_m
0,English,Indo-European,Germanic,372,1121
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335
9,Urdu,Indo-European,Indo-Aryan,78,168

In [ ]:
# Rows 0–4, columns 0–2 (language, family, branch)
# Remember that the ending point is exclusive

languages.iloc[0:5, 0:3]

                 language         family      branch
0                 English  Indo-European    Germanic
1        Mandarin Chinese   Sino-Tibetan     Sinitic
2                   Hindi  Indo-European  Indo-Aryan
3                 Spanish  Indo-European     Romance
4  Modern Standard Arabic   Afro-Asiatic     Semitic

In [24]:
# Stride: every 3rd language between rows 0 and 14

languages.iloc[0:14:3]

    language         family      branch  l1_speakers_m  l2_speakers_m
0    English  Indo-European    Germanic            372           1121
3    Spanish  Indo-European     Romance            487             75
6    Bengali  Indo-European  Indo-Aryan            234             43
9       Urdu  Indo-European  Indo-Aryan             78            168
12  Japanese        Japonic         NaN            124              2

In [25]:
# Negative indexing: the last 3 rows

languages.iloc[-3:]

           language          family   branch  l1_speakers_m  l2_speakers_m
12         Japanese         Japonic      NaN            124              2
13  Nigerian Pidgin  English Creole     Krio              5            116
14  Egyptian Arabic    Afro-Asiatic  Semitic             83             35

In [26]:
# Last row

languages.iloc[-1]

language         Egyptian Arabic
family              Afro-Asiatic
branch                   Semitic
l1_speakers_m                 83
l2_speakers_m                 35
Name: 14, dtype: object

We can also pass a second interior list in `.iloc` to specify columns

In [27]:
# First 3 rows, only language and family columns
languages.iloc[0:3, [0, 1]]

           language         family
0           English  Indo-European
1  Mandarin Chinese   Sino-Tibetan
2             Hindi  Indo-European

In [28]:
# 1st, 5th, and 9th row, only language and L2 speakers
languages.iloc[[0, 4, 8], [0, 4]]

                 language  l2_speakers_m
0                 English           1121
4  Modern Standard Arabic            335
8              Indonesian            177

### `.loc` — label-based indexing

`.loc[rows, columns]` uses **row index labels** and **column names**. Usually clearer than `.iloc` when column names are readable.

In [29]:
# 1st, 5th, and 9th row, only language and L2 speakers
languages.loc[[0, 4, 8], ['language', 'l2_speakers_m']]

                 language  l2_speakers_m
0                 English           1121
4  Modern Standard Arabic            335
8              Indonesian            177

In [30]:
# Top 5, language and family

languages.loc[0:4,['language', 'family']]

                 language         family
0                 English  Indo-European
1        Mandarin Chinese   Sino-Tibetan
2                   Hindi  Indo-European
3                 Spanish  Indo-European
4  Modern Standard Arabic   Afro-Asiatic

> ⚠️ **`.loc` vs `.iloc`**  
> `.loc[0:4]` is **inclusive** on both ends → rows 0, 1, 2, 3, 4  
> `.iloc[0:4]` is **exclusive** on the right → rows 0, 1, 2, 3

On a side note, this would also work if your rows had custom labels, say if you were using unique ids for your datapoints in each row.

### Selecting single cells

You can use both `.loc` and `.iloc` to select single cells

In [31]:
# Find the 11th language with most speakers
# hint: the dataframe is sorted based on total L1+L2 speakers

languages.iloc[10, 0]

'Russian'

In [32]:
languages.columns

Index(['language', 'family', 'branch', 'l1_speakers_m', 'l2_speakers_m'], dtype='str')

In [33]:
# how many L1 speakers does this language have?

languages.loc[10, 'l1_speakers_m']

133

What is `np.int64(133)`?

That's just how pandas displays a single cell!. It's telling you the value is 133 and its type is np.int64 (a NumPy 64-bit integer, which is what pandas uses internally for integer columns as we have seen in `dtypes`).

In [ ]:
# we can fix that with a little data type transformation

int(languages.loc[10, 'l1_speakers_m'])

In [34]:
languages.loc[10, 'family']

'Indo-European'

In [35]:
languages.iloc[5, 0]

'French'

---

## 4. Boolean (conditional) subsetting

The most powerful way to filter rows is with a **boolean mask** — a Series of True/False values that you use to index the DataFrame.

Let's see how this plays out: 

**Find all the Indo-European languages in this df**

In [36]:
# Step 1: create the mask
languages['family'] == 'Indo-European'

0      True
1     False
2      True
3      True
4     False
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12    False
13    False
14    False
Name: family, dtype: bool

In [37]:
# Step 2: use the mask to filter
ie = languages[languages['family'] == 'Indo-European']

In [39]:
print(ie.shape)

(9, 5)

In [40]:
print(languages.shape)

(15, 5)

In [41]:
ie.head()

  language         family      branch  l1_speakers_m  l2_speakers_m
0  English  Indo-European    Germanic            372           1121
2    Hindi  Indo-European  Indo-Aryan            347            264
3  Spanish  Indo-European     Romance            487             75
5   French  Indo-European     Romance             75            258
6  Bengali  Indo-European  Indo-Aryan            234             43

**Find all the *NON* Indo-European languages in this df**

In [42]:
not_ie = languages[languages['family'] != 'Indo-European']

In [43]:
not_ie.shape

(6, 5)

In [ ]:
# Inequality

not_ie = languages[languages['family'] != 'Indo-European']
print(not_ie.shape)
not_ie.head(3)

### Combining conditions

Use `&` (AND) and `|` (OR). **Always wrap each condition in parentheses.**

In [44]:
# Indo-European languages that are also Romance languages

ie_romance = languages[
    (languages['family'] == 'Indo-European') &
    (languages['branch'] == 'Romance')
]

print(ie_romance.shape)
ie_romance

(3, 5)

     language         family   branch  l1_speakers_m  l2_speakers_m
3     Spanish  Indo-European  Romance            487             75
5      French  Indo-European  Romance             75            258
7  Portuguese  Indo-European  Romance            252             18

In [ ]:
ie_romance = languages[(languages['family'] == 'Indo-European') & (languages['branch'] == 'Romance')]

In [45]:
# Romance or Semitic languages

semitic_romance = languages[
    (languages['branch'] == 'Semitic') |
    (languages['branch'] == 'Romance')
]

print(semitic_romance.shape)
semitic_romance

(5, 5)

,language,family,branch,l1_speakers_m,l2_speakers_m
3,Spanish,Indo-European,Romance,487,75
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335
5,French,Indo-European,Romance,75,258
7,Portuguese,Indo-European,Romance,252,18
14,Egyptian Arabic,Afro-Asiatic,Semitic,83,35

### `.str` accessor — filtering on string content

For string columns, pandas offers a `.str` accessor that unlocks methods like `.contains()`, `.startswith()`, `.lower()`, etc. Very useful for text analysis.

In [47]:
# Languages that contain 'Arabic' in their name
languages[languages['language'].str.contains('Arabic', case=False)]

,language,family,branch,l1_speakers_m,l2_speakers_m
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335
14,Egyptian Arabic,Afro-Asiatic,Semitic,83,35

---
## 5. Adding and modifying columns

### Creating a new column

We can create a new column by combining or transforming existing columns. This is very useful for storing transformations that we do with our data for later use.

In [ ]:
# Compute total speakers (L1 + L2) and add it as a new column
languages['total_speakers'] = languages['l1_speakers_m'] + languages['l2_speakers_m']

In [49]:
print(languages.shape)

(15, 6)

In [50]:
languages.head()

,language,family,branch,l1_speakers_m,l2_speakers_m,total_speakers
0,English,Indo-European,Germanic,372,1121,1493
1,Mandarin Chinese,Sino-Tibetan,Sinitic,988,194,1182
2,Hindi,Indo-European,Indo-Aryan,347,264,611
3,Spanish,Indo-European,Romance,487,75,562
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335,335

In [51]:
languages[['language', 'l1_speakers_m', 'l2_speakers_m', 'total_speakers']]

                  language  l1_speakers_m  l2_speakers_m  total_speakers
0                  English            372           1121            1493
1         Mandarin Chinese            988            194            1182
2                    Hindi            347            264             611
3                  Spanish            487             75             562
4   Modern Standard Arabic              0            335             335
5                   French             75            258             333
6                  Bengali            234             43             277
7               Portuguese            252             18             270
8               Indonesian             78            177             255
9                     Urdu             78            168             246
10                 Russian            133             77             210
11         Standard German             76             57             133
12                Japanese            124              2             126
13         Nigerian Pidgin              5            116             121
14         Egyptian Arabic             83             35             118

### Renaming columns

We can rename our columns. Here, I am not sure if I am happy with `total_speakers`, it would match the rest of the col names better if it was `total_speakers_m` showing that it is in millions

In [52]:
# Rename with a dictionary: {old_name: new_name}
# inplace=True modifies the DataFrame directly instead of returning a copy
languages.rename(columns={
    'total_speakers':   'total_speakers_m'
}, inplace=True)

languages.columns

Index(['language', 'family', 'branch', 'l1_speakers_m', 'l2_speakers_m',
       'total_speakers_m'],
      dtype='str')

### Deleting a column

Dropping a column with `.drop()` returns a copy by default, meaning that it does not modify the dataframe. We need to either create a new dataframe with fewer columns or use `inplace=True` argument to change the df.

In [53]:
languages.shape

(15, 6)

In [54]:
languages.drop(columns=['family'])

,language,branch,l1_speakers_m,l2_speakers_m,total_speakers_m
0,English,Germanic,372,1121,1493
1,Mandarin Chinese,Sinitic,988,194,1182
2,Hindi,Indo-Aryan,347,264,611
3,Spanish,Romance,487,75,562
4,Modern Standard Arabic,Semitic,0,335,335
5,French,Romance,75,258,333
6,Bengali,Indo-Aryan,234,43,277
7,Portuguese,Romance,252,18,270
8,Indonesian,Malayo-Polynesian,78,177,255
9,Urdu,Indo-Aryan,78,168,246
10,Russian,Balto-Slavic,133,77,210
11,Standard German,Germanic,76,57,133
12,Japanese,NaN,124,2,126
13,Nigerian Pidgin,Krio,5,116,121
14,Egyptian Arabic,Semitic,83,35,118

In [55]:
languages.shape

(15, 6)

This will be handy for versioning on the fly and subsetting your dataframe

In [56]:
languages_v2 = languages.drop(columns=['family', 'branch'])
languages_v2.head()

                 language  l1_speakers_m  l2_speakers_m  total_speakers_m
0                 English            372           1121              1493
1        Mandarin Chinese            988            194              1182
2                   Hindi            347            264               611
3                 Spanish            487             75               562
4  Modern Standard Arabic              0            335               335

---

## 6. Counting, sorting, and grouping

### `.value_counts()` — frequency table for one column

In [57]:
languages['language'].value_counts()

language
English                   1
Mandarin Chinese          1
Hindi                     1
Spanish                   1
Modern Standard Arabic    1
French                    1
Bengali                   1
Portuguese                1
Indonesian                1
Urdu                      1
Russian                   1
Standard German           1
Japanese                  1
Nigerian Pidgin           1
Egyptian Arabic           1
Name: count, dtype: int64

`value_counts()` by default groups unique items together

In [58]:
languages["branch"].value_counts()

branch
Indo-Aryan           3
Romance              3
Germanic             2
Semitic              2
Sinitic              1
Malayo-Polynesian    1
Balto-Slavic         1
Krio                 1
Name: count, dtype: int64

This means that we can use `value_counts()` to find the top 3 most frequent language family branches in our dataset

In [59]:
languages["branch"].value_counts().head(3)

branch
Indo-Aryan    3
Romance       3
Germanic      2
Name: count, dtype: int64

In [60]:
# why not this?

languages["branch"].head(3).value_counts()

branch
Germanic      1
Sinitic       1
Indo-Aryan    1
Name: count, dtype: int64

In [61]:
languages["branch"].head(3)

0      Germanic
1       Sinitic
2    Indo-Aryan
Name: branch, dtype: str

The order in which we chain functions matter! In the second example, we got the counts of different branches among the top 3 languages

### `.unique()` and `.nunuque()`

`unique()` returns the actual unique values, `nunique()` gives you the number of unique values in your data

In [62]:
# How many unique language families are in our dataset?
languages['family'].nunique()

6

In [63]:
# What are the unique language families?
languages['family'].unique()

<StringArray>
[ 'Indo-European',   'Sino-Tibetan',   'Afro-Asiatic',   'Austronesian',
        'Japonic', 'English Creole']
Length: 6, dtype: str

### `.sort_values()` — sort by a column

In [64]:
# Sort by total speakers, largest first
languages[['language', 'total_speakers_m']].sort_values('total_speakers_m', ascending=False)

                  language  total_speakers_m
0                  English              1493
1         Mandarin Chinese              1182
2                    Hindi               611
3                  Spanish               562
4   Modern Standard Arabic               335
5                   French               333
6                  Bengali               277
7               Portuguese               270
8               Indonesian               255
9                     Urdu               246
10                 Russian               210
11         Standard German               133
12                Japanese               126
13         Nigerian Pidgin               121
14         Egyptian Arabic               118

<div style="background: rgba(167, 139, 250, 0.12); border-radius: 6px; padding: 0.6em 1em; margin: 1.5em 0; font-weight: 500;">
  Did anything change in this sorting?
</div>




No, because this data was already sorted by total number of speakers in Wikipedia/Ethnologue. We just left out the L1+L2 column to show you how this transformation works.

Let's sort it by the **number of L1 speakers**:

In [65]:
# Sort by L1 speakers, smallest first
# to sort in ascending order, you can use the .sort_values() method without the ascending argument. It defaults to True
languages[['language', 'l1_speakers_m']].sort_values('l1_speakers_m', ascending=True)

                  language  l1_speakers_m
4   Modern Standard Arabic              0
13         Nigerian Pidgin              5
5                   French             75
11         Standard German             76
8               Indonesian             78
9                     Urdu             78
14         Egyptian Arabic             83
12                Japanese            124
10                 Russian            133
6                  Bengali            234
7               Portuguese            252
2                    Hindi            347
0                  English            372
3                  Spanish            487
1         Mandarin Chinese            988

Arabic (Modern Standard) is a special case — it has *no* L1 speakers because no one grows up speaking the standardised written form natively; speakers first acquire a regional dialect.

Do we have to use `.sort_values()` functions with numbers only?

In [66]:
# Sort alphabetically by language name
languages.sort_values('language').head(10)

,language,family,branch,l1_speakers_m,l2_speakers_m,total_speakers_m
6,Bengali,Indo-European,Indo-Aryan,234,43,277
14,Egyptian Arabic,Afro-Asiatic,Semitic,83,35,118
0,English,Indo-European,Germanic,372,1121,1493
5,French,Indo-European,Romance,75,258,333
2,Hindi,Indo-European,Indo-Aryan,347,264,611
8,Indonesian,Austronesian,Malayo-Polynesian,78,177,255
12,Japanese,Japonic,NaN,124,2,126
1,Mandarin Chinese,Sino-Tibetan,Sinitic,988,194,1182
4,Modern Standard Arabic,Afro-Asiatic,Semitic,0,335,335
13,Nigerian Pidgin,English Creole,Krio,5,116,121

In [67]:
# Sort alphabetically by family, then by total speakers within each family
languages.sort_values(['family', 'total_speakers_m'], ascending=[True, False])[['language', 'family', 'total_speakers_m']]

                  language          family  total_speakers_m
4   Modern Standard Arabic    Afro-Asiatic               335
14         Egyptian Arabic    Afro-Asiatic               118
8               Indonesian    Austronesian               255
13         Nigerian Pidgin  English Creole               121
0                  English   Indo-European              1493
2                    Hindi   Indo-European               611
3                  Spanish   Indo-European               562
5                   French   Indo-European               333
6                  Bengali   Indo-European               277
7               Portuguese   Indo-European               270
9                     Urdu   Indo-European               246
10                 Russian   Indo-European               210
11         Standard German   Indo-European               133
12                Japanese         Japonic               126
1         Mandarin Chinese    Sino-Tibetan              1182

### `.groupby()` — split, apply, combine

`groupby()` splits the DataFrame into groups based on a column, **applies an aggregate function** to each group, then combines the results. Think of it as a pivot table.

In [68]:
# Number of languages per family in our dataset
languages.groupby('family')['language'].count().sort_values(ascending=False)

family
Indo-European     9
Afro-Asiatic      2
Austronesian      1
English Creole    1
Japonic           1
Sino-Tibetan      1
Name: language, dtype: int64

Let's look at this in more detail, to understand what the code is doing

1. `.groupby('family')` -> groups our dataset by family
2. `['language'].count()` -> counts how many languages fall into each grouping
3. `.sort_values(ascending=False)` -> sorts the counts by descending order

In [69]:
# Average L1 speakers per language family
languages.groupby('family')['l1_speakers_m'].mean().round(2).sort_values(ascending=False)

family
Sino-Tibetan      988.00
Indo-European     228.22
Japonic           124.00
Austronesian       78.00
Afro-Asiatic       41.50
English Creole      5.00
Name: l1_speakers_m, dtype: float64

In [70]:
# Total speakers (L1 + L2) per branch
languages.groupby('branch')['total_speakers_m'].sum().sort_values(ascending=False)

branch
Germanic             1626
Sinitic              1182
Romance              1165
Indo-Aryan           1134
Semitic               453
Malayo-Polynesian     255
Balto-Slavic          210
Krio                  121
Name: total_speakers_m, dtype: int64

---

## 7. Missing Data

Real datasets almost always have gaps. Pandas represents missing values as `NaN` (Not a Number).

In [71]:
# Check how many missing values per column
languages.isna().sum()

language            0
family              0
branch              1
l1_speakers_m       0
l2_speakers_m       0
total_speakers_m    0
dtype: int64

We have one missing value in the branch column, meaning that one of the 15 languages does not have a branch

In [72]:
# Show only rows where any value is missing
languages[languages.isna().any(axis=1)]

    language   family branch  l1_speakers_m  l2_speakers_m  total_speakers_m
12  Japanese  Japonic    NaN            124              2               126

This makes sense! Japanese is considered a language isolate

In [73]:
# Drop rows where 'branch' is missing
languages_with_branch = languages.dropna(subset=['branch'])
print(languages_with_branch.shape)
languages_with_branch[['language', 'branch']]

(14, 6)

                  language             branch
0                  English           Germanic
1         Mandarin Chinese            Sinitic
2                    Hindi         Indo-Aryan
3                  Spanish            Romance
4   Modern Standard Arabic            Semitic
5                   French            Romance
6                  Bengali         Indo-Aryan
7               Portuguese            Romance
8               Indonesian  Malayo-Polynesian
9                     Urdu         Indo-Aryan
10                 Russian       Balto-Slavic
11         Standard German           Germanic
13         Nigerian Pidgin               Krio
14         Egyptian Arabic            Semitic

In [74]:
languages_with_branch.isna().sum()

language            0
family              0
branch              0
l1_speakers_m       0
l2_speakers_m       0
total_speakers_m    0
dtype: int64

---

## 8. Practice Challenges

<div style="background: rgba(167, 139, 250, 0.12); border-radius: 6px; padding: 0.6em 1em; margin: 1.5em 0; font-weight: 500;">
  Challenge 1: Explain in your own words what the code below shows
</div>

In [ ]:
languages['family'].value_counts()

**Answer:** Of the top 15 languages with the highest number of L1+L2 speakers, 9 of them are Indo-European.

<div style="background: rgba(167, 139, 250, 0.12); border-radius: 6px; padding: 0.6em 1em; margin: 1.5em 0; font-weight: 500;">
  Challenge 2: Which Indo-European language has the most L1 speakers?
</div>

In [ ]:
### YOUR CODE HERE

In [ ]:
# Filter to Indo-European languages only
languages[languages['family'] == 'Indo-European']

In [ ]:
# First we create a new dataframe, which is a subset of the languages df, where the language family is Indo-European
ie = languages[languages['family'] == 'Indo-European']

In [ ]:
# then we sort this df based on number of L1 speakers, highest first -> .sort_values()
ie = ie.sort_values('l1_speakers_m', ascending=False)
ie

In [ ]:
# then we return only the input of the cell at row 0 (highest count), column 0 (language name)
ie.iloc[0]['language']

In [ ]:
# we could have sorted the df on the fly as well
ie.sort_values('l1_speakers_m', ascending=False).iloc[0]['language']

In [ ]:
# Or if you want to show the full row:
ie.loc[ie['l1_speakers_m'].idxmax()]

<div style="background: rgba(167, 139, 250, 0.12); border-radius: 6px; padding: 0.6em 1em; margin: 1.5em 0; font-weight: 500;">
  Challenge 3: Which language has the biggest gap between L1 and L2 speakers?
</div>

In [ ]:
### YOUR CODE HERE

In [ ]:
# Biggest absolute gap between L2 and L1
languages['l2_l1_gap'] = languages['l2_speakers_m'] - languages['l1_speakers_m']
languages.sort_values('l2_l1_gap', ascending=False)[['language', 'l1_speakers_m', 'l2_speakers_m', 'l2_l1_gap']]

<div style="background: rgba(167, 139, 250, 0.12); border-radius: 6px; padding: 0.6em 1em; margin: 1.5em 0; font-weight: 500;">
  Challenge 4: Which language attracts the most L2 speakers <em>relative to its native speaker base</em>?
</div>

In [ ]:
### YOUR CODE HERE

In [ ]:
# L2 speakers as a ratio of L1 speakers (how much does a language expand beyond its native/L1 base"?)
# We exclude Arabic (Modern Standard) since it has 0 L1 speakers — dividing by zero gives inf
langs_with_l1 = languages[languages['l1_speakers_m'] > 0].copy()

# we calculate the ratios and round to two decimal places
langs_with_l1['l2_per_l1'] = (langs_with_l1['l2_speakers_m'] / langs_with_l1['l1_speakers_m']).round(2)

# we are sorting and also limiting how many of the columns we would like to show here.
langs_with_l1.sort_values('l2_per_l1', ascending=False)[['language', 'l1_speakers_m', 'l2_speakers_m', 'l2_per_l1']]

> There are about 23 L2 speakers of Nigerian Pidgen for each L1 speaker

Nigerian Pidgin makes sense considering that it is a lingua franca in Nigeria (and to a smaller extent in West and Central Africa) across different ethnic groups and communities, each of which have their own native languages.

> What about French? Isn't that a little surprising that there are 3.4 times more L2 speakers than L1?

It is because French is a very popular acquired language!

Also, please note that this dataset classifies creole French languages separetely from French spoken in France, Canada, and a handful other countries. When we speak about French in this dataset, we are missing about 15 million creole French speakers globally, most prominently 12 million speakers of Haitian Creole.

> What does it mean for the ratios to be below 1?

It means the language has more native speakers than L2 learners — most people who speak it grew up with it rather than acquired it as an additional language. Mandarin Chinese (0.2) is the clearest example: with nearly a billion L1 speakers, relatively few people learn it as a second language despite its size.

---
## 9. Key points to remember

| Concept | Code |
|---|---|
| Load CSV | `pd.read_csv('file.csv')` |
| First N rows | `df.head(N)` |
| Shape | `df.shape` |
| Column names | `df.columns` |
| Data types | `df.dtypes` |
| Summary stats | `df.describe()` |
| Select column | `df['col']` (Series) |
| Select columns | `df[['col1', 'col2']]` (DataFrame) |
| Position indexing | `df.iloc[rows, cols]` |
| Label indexing | `df.loc[rows, cols]` |
| Boolean filter | `df[df['col'] == value]` |
| AND / OR | `(cond1) & (cond2)` / `(cond1) \| (cond2)` |
| String search | `df['col'].str.contains('text')` |
| New column | `df['new'] = ...` |
| Rename columns | `df.rename(columns={'old': 'new'})` |
| Count values | `df['col'].value_counts()` |
| Group + aggregate | `df.groupby('col')['other'].mean()` |
| Sort | `df.sort_values('col', ascending=False)` |
| Missing values | `df.isna().sum()` / `df.dropna()` / `df.fillna()` |